// Generated by gencpp from file perception/Landmark.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_LANDMARK_H
#define PERCEPTION_MESSAGE_LANDMARK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception
{
template <class ContainerAllocator>
struct Landmark_
{
  typedef Landmark_<ContainerAllocator> Type;

  Landmark_()
    : x(0.0)
    , y(0.0)
    , signature(0)  {
    }
  Landmark_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , signature(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef int32_t _signature_type;
  _signature_type signature;





  typedef boost::shared_ptr< ::perception::Landmark_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::Landmark_<ContainerAllocator> const> ConstPtr;

}; // struct Landmark_

typedef ::perception::Landmark_<std::allocator<void> > Landmark;

typedef boost::shared_ptr< ::perception::Landmark > LandmarkPtr;
typedef boost::shared_ptr< ::perception::Landmark const> LandmarkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::Landmark_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::Landmark_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception::Landmark_<ContainerAllocator1> & lhs, const ::perception::Landmark_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.signature == rhs.signature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception::Landmark_<ContainerAllocator1> & lhs, const ::perception::Landmark_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception::Landmark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Landmark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Landmark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Landmark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Landmark_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Landmark_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e3688e586de9cd73537826cf84070c3";
  }

  static const char* value(const ::perception::Landmark_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e3688e586de9cd7ULL;
  static const uint64_t static_value2 = 0x3537826cf84070c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/Landmark";
  }

  static const char* value(const ::perception::Landmark_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"int32 signature\n"
;
  }

  static const char* value(const ::perception::Landmark_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::Landmark_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.signature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Landmark_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::Landmark_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::Landmark_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "signature: ";
    Printer<int32_t>::stream(s, indent + "  ", v.signature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_LANDMARK_H
