// Generated by gencpp from file perception/Landmarks.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_LANDMARKS_H
#define PERCEPTION_MESSAGE_LANDMARKS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <perception/Landmark.h>

namespace perception
{
template <class ContainerAllocator>
struct Landmarks_
{
  typedef Landmarks_<ContainerAllocator> Type;

  Landmarks_()
    : landmarks()  {
    }
  Landmarks_(const ContainerAllocator& _alloc)
    : landmarks(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::perception::Landmark_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::perception::Landmark_<ContainerAllocator> >> _landmarks_type;
  _landmarks_type landmarks;





  typedef boost::shared_ptr< ::perception::Landmarks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::Landmarks_<ContainerAllocator> const> ConstPtr;

}; // struct Landmarks_

typedef ::perception::Landmarks_<std::allocator<void> > Landmarks;

typedef boost::shared_ptr< ::perception::Landmarks > LandmarksPtr;
typedef boost::shared_ptr< ::perception::Landmarks const> LandmarksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::Landmarks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::Landmarks_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception::Landmarks_<ContainerAllocator1> & lhs, const ::perception::Landmarks_<ContainerAllocator2> & rhs)
{
  return lhs.landmarks == rhs.landmarks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception::Landmarks_<ContainerAllocator1> & lhs, const ::perception::Landmarks_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception::Landmarks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Landmarks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Landmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Landmarks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Landmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Landmarks_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49e711d7c1f85a6a1a9bc1177447407c";
  }

  static const char* value(const ::perception::Landmarks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49e711d7c1f85a6aULL;
  static const uint64_t static_value2 = 0x1a9bc1177447407cULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/Landmarks";
  }

  static const char* value(const ::perception::Landmarks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Landmark[] landmarks\n"
"\n"
"================================================================================\n"
"MSG: perception/Landmark\n"
"float32 x\n"
"float32 y\n"
"int32 signature\n"
;
  }

  static const char* value(const ::perception::Landmarks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::Landmarks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.landmarks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Landmarks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::Landmarks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::Landmarks_<ContainerAllocator>& v)
  {
    s << indent << "landmarks[]" << std::endl;
    for (size_t i = 0; i < v.landmarks.size(); ++i)
    {
      s << indent << "  landmarks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception::Landmark_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_LANDMARKS_H
