# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from perception/Observations.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import perception.msg

class Observations(genpy.Message):
  _md5sum = "a77531c2f2c5a83066e66b6f9d29109c"
  _type = "perception/Observations"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Observation[] observations

================================================================================
MSG: perception/Observation
float32 range
float32 bearing
int32 signature
"""
  __slots__ = ['observations']
  _slot_types = ['perception/Observation[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       observations

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Observations, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.observations is None:
        self.observations = []
    else:
      self.observations = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.observations)
      buff.write(_struct_I.pack(length))
      for val1 in self.observations:
        _x = val1
        buff.write(_get_struct_2fi().pack(_x.range, _x.bearing, _x.signature))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.observations is None:
        self.observations = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.observations = []
      for i in range(0, length):
        val1 = perception.msg.Observation()
        _x = val1
        start = end
        end += 12
        (_x.range, _x.bearing, _x.signature,) = _get_struct_2fi().unpack(str[start:end])
        self.observations.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.observations)
      buff.write(_struct_I.pack(length))
      for val1 in self.observations:
        _x = val1
        buff.write(_get_struct_2fi().pack(_x.range, _x.bearing, _x.signature))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.observations is None:
        self.observations = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.observations = []
      for i in range(0, length):
        val1 = perception.msg.Observation()
        _x = val1
        start = end
        end += 12
        (_x.range, _x.bearing, _x.signature,) = _get_struct_2fi().unpack(str[start:end])
        self.observations.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2fi = None
def _get_struct_2fi():
    global _struct_2fi
    if _struct_2fi is None:
        _struct_2fi = struct.Struct("<2fi")
    return _struct_2fi
